CREATE TABLE T_ROUTE_RTE 
(RTE_DESTINATION VARCHAR(32),  
 RTE_CODE        CHAR(16)); 

INSERT INTO T_ROUTE_RTE VALUES ('albania-Mobile', '0035538');  
INSERT INTO T_ROUTE_RTE VALUES ('albania-Mobile', '0035569');  
INSERT INTO T_ROUTE_RTE VALUES ('albania-Mobile', '0035560');  
INSERT INTO T_ROUTE_RTE VALUES ('SFR-Mobile',     '0077280'); 
INSERT INTO T_ROUTE_RTE VALUES ('SFR-Mobile',     '0077390');  
INSERT INTO T_ROUTE_RTE VALUES ('BOUYGE_TEL',     '0078452'); 