CREATE TABLE T_NUMERO_NMR 
(
    NMR INTEGER
); 

INSERT INTO T_NUMERO_NMR VALUES (1); 
INSERT INTO T_NUMERO_NMR VALUES (2);
INSERT INTO T_NUMERO_NMR VALUES (3); 
INSERT INTO T_NUMERO_NMR VALUES (5); 
INSERT INTO T_NUMERO_NMR VALUES (6); 
INSERT INTO T_NUMERO_NMR VALUES (8); 
INSERT INTO T_NUMERO_NMR VALUES (9); 
INSERT INTO T_NUMERO_NMR VALUES (10); 
INSERT INTO T_NUMERO_NMR VALUES (11); 
INSERT INTO T_NUMERO_NMR VALUES (12); 
INSERT INTO T_NUMERO_NMR VALUES (14); 
INSERT INTO T_NUMERO_NMR VALUES (15); 

