-- Question 1

SELECT *
FROM   T_CELKO_TEN_IN_ON_TIO
WHERE    CASE WHEN ABS(TIO_1) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_2) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_3) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_4) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_5) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_6) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_7) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_8) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_9 )> 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_10) > 0 THEN 1 ELSE 0 END = 1 ;

-- Question 2
SELECT *
FROM   T_CELKO_TEN_IN_ON_TIO
WHERE    CASE WHEN ABS(TIO_1) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_2) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_3) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_4) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_5) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_6) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_7) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_8) > 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_9 )> 0 THEN 1 ELSE 0 END
       + CASE WHEN ABS(TIO_10) > 0 THEN 1 ELSE 0 END = 1 
  AND TIO_1 + TIO_2 + TIO_3 + TIO_4 + TIO_5 + TIO_6 + TIO_7 + TIO_8 + TIO_9 + TIO_10 = 1 ;