-- Question 1
SELECT *
FROM   T_CLIENT_CLI
WHERE  ((EXTRACT(MONTH FROM CLI_DATE_NAISSANCE)) + EXTRACT(DAY FROM CLI_DATE_NAISSANCE))
AND CLI_DATE_NAISSANCE BETWEEN "21-02" AND "20-03";

-- Question 2 

SELECT *
FROM   T_CLIENT_CLI
WHERE  ((EXTRACT(MONTH FROM CLI_DATE_NAISSANCE)) + EXTRACT(DAY FROM CLI_DATE_NAISSANCE))
AND CLI_DATE_NAISSANCE BETWEEN "21-12" AND "20-01";
