CREATE TABLE T_AMORTISSEMENT_AMT
(AMT_FIN     CHAR(6), 
 AMT_FIN_Y2K CHAR(10)
); 

INSERT INTO T_AMORTISSEMENT_AMT (AMT_FIN) VALUES ('990601');
INSERT INTO T_AMORTISSEMENT_AMT (AMT_FIN) VALUES ('970201'); 
INSERT INTO T_AMORTISSEMENT_AMT (AMT_FIN) VALUES ('021201');
INSERT INTO T_AMORTISSEMENT_AMT (AMT_FIN) VALUES ('941101'); 
INSERT INTO T_AMORTISSEMENT_AMT (AMT_FIN) VALUES ('920715'); 

select * from T_AMORTISSEMENT_AMT;



