CREATE TABLE T_CHAMBRE_CHB
(
    CHB_NUM INTEGER
); 

CREATE TABLE T_PLANNING_PLN 
(
    PLN_JOUR  DATE, 
    CHB_NUM   INTEGER, 
    PLN_LIBRE CHAR(5)
); 

INSERT INTO T_CHAMBRE_CHB VALUES (1) ;
INSERT INTO T_CHAMBRE_CHB VALUES (2) ;
INSERT INTO T_CHAMBRE_CHB VALUES (3) ;
INSERT INTO T_CHAMBRE_CHB VALUES (4) ; 

INSERT INTO T_PLANNING_PLN VALUES ('2000-01-12', 1, 'False') ;
INSERT INTO T_PLANNING_PLN VALUES ('2000-01-12', 2, 'False') ;
INSERT INTO T_PLANNING_PLN VALUES ('2000-01-13', 1, 'False') ;
INSERT INTO T_PLANNING_PLN VALUES ('2000-01-13', 2, 'False') ;
INSERT INTO T_PLANNING_PLN VALUES ('2000-01-13', 4, 'True' ) ; 

